// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: c1/connector/v2/jira_cloud_external_ticket.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *CustomField) Reset() {
	*x = CustomField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c1_connector_v2_jira_cloud_external_ticket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomField) ProtoMessage() {}

func (x *CustomField) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connector_v2_jira_cloud_external_ticket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomField.ProtoReflect.Descriptor instead.
func (*CustomField) Descriptor() ([]byte, []int) {
	return file_c1_connector_v2_jira_cloud_external_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *CustomField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type JCIssueTypeProject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId   string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectName string `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	ProjectKey  string `protobuf:"bytes,3,opt,name=project_key,json=projectKey,proto3" json:"project_key,omitempty"`
}

func (x *JCIssueTypeProject) Reset() {
	*x = JCIssueTypeProject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c1_connector_v2_jira_cloud_external_ticket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JCIssueTypeProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JCIssueTypeProject) ProtoMessage() {}

func (x *JCIssueTypeProject) ProtoReflect() protoreflect.Message {
	mi := &file_c1_connector_v2_jira_cloud_external_ticket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JCIssueTypeProject.ProtoReflect.Descriptor instead.
func (*JCIssueTypeProject) Descriptor() ([]byte, []int) {
	return file_c1_connector_v2_jira_cloud_external_ticket_proto_rawDescGZIP(), []int{1}
}

func (x *JCIssueTypeProject) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *JCIssueTypeProject) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *JCIssueTypeProject) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

var File_c1_connector_v2_jira_cloud_external_ticket_proto protoreflect.FileDescriptor

var file_c1_connector_v2_jira_cloud_external_ticket_proto_rawDesc = []byte{
	0x0a, 0x30, 0x63, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x76,
	0x32, 0x2f, 0x6a, 0x69, 0x72, 0x61, 0x5f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x65, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0f, 0x63, 0x31, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x2e, 0x76, 0x32, 0x22, 0x21, 0x0a, 0x0b, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x77, 0x0a, 0x12, 0x4a, 0x43, 0x49, 0x73, 0x73, 0x75,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x42,
	0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f,
	0x6e, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x6f, 0x6e, 0x65, 0x2f, 0x62, 0x61, 0x74, 0x6f, 0x6e,
	0x2d, 0x6a, 0x69, 0x72, 0x61, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_c1_connector_v2_jira_cloud_external_ticket_proto_rawDescOnce sync.Once
	file_c1_connector_v2_jira_cloud_external_ticket_proto_rawDescData = file_c1_connector_v2_jira_cloud_external_ticket_proto_rawDesc
)

func file_c1_connector_v2_jira_cloud_external_ticket_proto_rawDescGZIP() []byte {
	file_c1_connector_v2_jira_cloud_external_ticket_proto_rawDescOnce.Do(func() {
		file_c1_connector_v2_jira_cloud_external_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(file_c1_connector_v2_jira_cloud_external_ticket_proto_rawDescData)
	})
	return file_c1_connector_v2_jira_cloud_external_ticket_proto_rawDescData
}

var file_c1_connector_v2_jira_cloud_external_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_c1_connector_v2_jira_cloud_external_ticket_proto_goTypes = []interface{}{
	(*CustomField)(nil),        // 0: c1.connector.v2.CustomField
	(*JCIssueTypeProject)(nil), // 1: c1.connector.v2.JCIssueTypeProject
}
var file_c1_connector_v2_jira_cloud_external_ticket_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_c1_connector_v2_jira_cloud_external_ticket_proto_init() }
func file_c1_connector_v2_jira_cloud_external_ticket_proto_init() {
	if File_c1_connector_v2_jira_cloud_external_ticket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_c1_connector_v2_jira_cloud_external_ticket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_c1_connector_v2_jira_cloud_external_ticket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JCIssueTypeProject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_c1_connector_v2_jira_cloud_external_ticket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_c1_connector_v2_jira_cloud_external_ticket_proto_goTypes,
		DependencyIndexes: file_c1_connector_v2_jira_cloud_external_ticket_proto_depIdxs,
		MessageInfos:      file_c1_connector_v2_jira_cloud_external_ticket_proto_msgTypes,
	}.Build()
	File_c1_connector_v2_jira_cloud_external_ticket_proto = out.File
	file_c1_connector_v2_jira_cloud_external_ticket_proto_rawDesc = nil
	file_c1_connector_v2_jira_cloud_external_ticket_proto_goTypes = nil
	file_c1_connector_v2_jira_cloud_external_ticket_proto_depIdxs = nil
}
