// Code generated by baton-sdk. DO NOT EDIT!!!
package config

import "reflect" 

type Jira struct {
	JiraUrl string `mapstructure:"jira-url"`
	JiraEmail string `mapstructure:"jira-email"`
	JiraApiToken string `mapstructure:"jira-api-token"`
	JiraProjectKeys []string `mapstructure:"jira-project-keys"`
	SkipProjectParticipants bool `mapstructure:"skip-project-participants"`
	Ticketing bool `mapstructure:"ticketing"`
	SkipCustomerUser bool `mapstructure:"skip-customer-user"`
	AtlassianOrgid string `mapstructure:"atlassian-orgId"`
	AtlassianApiToken string `mapstructure:"atlassian-api-token"`
}

func (c* Jira) findFieldByTag(tagValue string) (any, bool) {
	v := reflect.ValueOf(c).Elem() // Dereference pointer to struct
	t := v.Type()

	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		tag := field.Tag.Get("mapstructure")

		if tag == tagValue {
			return v.Field(i).Interface(), true
		}
	}
	return nil, false
}

func (c *Jira) GetStringSlice(fieldName string) []string {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return []string{}
	}
	t, ok := v.([]string)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Jira) GetString(fieldName string) string {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return ""
	}
	t, ok := v.(string)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Jira) GetInt(fieldName string) int {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return 0
	}
	t, ok := v.(int)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Jira) GetBool(fieldName string) bool {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return false
	}
	t, ok := v.(bool)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Jira) GetStringMap(fieldName string) map[string]any {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return map[string]any{}
	}
	t, ok := v.(map[string]any)
	if !ok {
		panic("wrong type")
	}
	return t
}
