name: Output connector capabilities

on:
  push:
    branches:
      - main

jobs:
  calculate-capabilities:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELENG_GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: go build -o connector ./cmd/baton-jira

      - name: Run and save output
        env:
          BATON_JIRA_API_TOKEN: example
          BATON_JIRA_EMAIL: example
          BATON_JIRA_URL: https://example.com
        run: ./connector capabilities > baton_capabilities.json

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Updating baton capabilities.'
          add: 'baton_capabilities.json'
